name: Build QMK firmware
on:
  push:
    paths:
    branches:
      - main
      - master
      - 'develop**'
jobs:

  Build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        board: [
          "jasonhazel/bad_wings:default",
          "jasonhazel/dust:default",
          "jasonhazel/satpad:default",
          "jasonhazel/glitch:default",
          "jasonhazel/crepe:default",
          "jasonhazel/lisa:default",
          "jasonhazel/skytoucher:default"
        ]
    steps:
      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          # change this to your repo
          repository: jasonhazel/qmk_hazel
          submodules: recursive


      - name: Build firmware
        run: |

          make ${{ matrix.board }}

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: firmware
          path: |
            *.hex
            *.bin
            *.uf2

